// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "bintaro-university-admission/internal/ui/components"

func indexMainContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"welcome-section\"><h2>Welcome to Bintaro University Admission</h2><p>Track your admission progress and stay updated with important notifications.</p></div><script>\n\t\tfunction toggleDropdown() {\n\t\t\tconst dropdown = document.getElementById(\"dropdown\");\n\t\t\tconst hamburgerBtn = document.querySelector(\".hamburger-btn\");\n\n\t\t\tdropdown.classList.toggle(\"show\");\n\t\t\thamburgerBtn.classList.toggle(\"active\");\n\t\t}\n\n\t\t// Close dropdown when clicking outside\n\t\tdocument.addEventListener(\"click\", function (event) {\n\t\t\tconst hamburgerMenu = document.querySelector(\".hamburger-menu\");\n\t\t\tconst dropdown = document.getElementById(\"dropdown\");\n\t\t\tconst hamburgerBtn = document.querySelector(\".hamburger-btn\");\n\n\t\t\tif (!hamburgerMenu.contains(event.target)) {\n\t\t\t\tdropdown.classList.remove(\"show\");\n\t\t\t\thamburgerBtn.classList.remove(\"active\");\n\t\t\t}\n\t\t});\n\n\t\t// Prevent dropdown from closing when clicking inside it\n\t\tdocument.getElementById(\"dropdown\").addEventListener(\"click\", function (event) {\n\t\t\tevent.stopPropagation();\n\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = components.PageWrapper(components.PageWrapperProps{
			MainContent: indexMainContent(),
			DropDownItems: []templ.Component{
				components.DropDownItem(components.DropDownItemProps{
					Link: "/login",
					Text: "Login",
				}),
				components.DropDownItem(components.DropDownItemProps{
					Link: "/register",
					Text: "Register",
				}),
			},
			ErrorMessage: "",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
