name: PR Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-24.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
      - run: go version
      - name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.906
      - name: Format Templ code
        run: templ fmt . && templ generate
      - name: Format Go code
        run: go fmt ./...
      - uses: stefanzweifel/git-auto-commit-action@v6
      - name: Install GolangCI-Lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.2.1
      - run: golangci-lint ./...
